def get_skeleton(mode = "body"):
    if mode == "body":
        bodyparts2connect = [
            ("right_ankle", "right_knee"),
            ("right_knee", "right_hip"),
            ("left_ankle", "left_knee"),
            ("left_hip", "left_knee"),
            ("left_hip", "right_hip"),
            ("right_shoulder", "right_hip"),
            ("left_shoulder", "left_hip"),
            ("left_shoulder", "right_shoulder"),
            ("left_shoulder", "left_elbow"),
            ("right_shoulder", "right_elbow"),
            ("left_elbow", "left_wrist"),
            ("right_elbow", "right_wrist"),
            ("right_eye", "left_ear"),
            ("left_eye", "right_eye"),
            ("left_eye", "left_ear"),
            ("right_eye", "right_ear"),
            ("left_ear", "left_shoulder"),
            ("right_ear", "right_shoulder"),
            ("left_shoulder", "left_elbow"),
            ("right_shoulder", "right_elbow"),
        ]
        skeleton = [
            [16, 14],
            [14, 12],
            [17, 15],
            [15, 13],
            [12, 13],
            [6, 12],
            [7, 13],
            [6, 7],
            [6, 8],
            [7, 9],
            [8, 10],
            [9, 11],
            [2, 3],
            [1, 2],
            [1, 3],
            [2, 4],
            [3, 5],
            [4, 6],
            [5, 7],
        ]
    elif mode == "full_body":
        bodyparts2connect = [
            ("right_ankle", "right_knee"),
            ("right_knee", "right_hip"),
            ("left_ankle", "left_knee"),
            ("left_hip", "left_knee"),
            ("left_hip", "right_hip"),
            ("right_shoulder", "right_hip"),
            ("left_shoulder", "left_hip"),
            ("left_shoulder", "right_shoulder"),
            ("left_shoulder", "left_elbow"),
            ("right_shoulder", "right_elbow"),
            ("left_elbow", "left_wrist"),
            ("right_elbow", "right_wrist"),
            ("right_eye", "left_ear"),
            ("left_eye", "right_eye"),
            ("left_eye", "left_ear"),
            ("right_eye", "right_ear"),
            ("left_ear", "left_shoulder"),
            ("right_ear", "right_shoulder"),
            ("left_shoulder", "left_elbow"),
            ("right_shoulder", "right_elbow"),
            ("left_wrist_hand", "left_thumb_1"),
            ("left_thumb_1", "left_thumb_2"),
            ("left_thumb_2", "left_thumb_3"),
            ("left_thumb_3", "left_thumb_4"),
            ("left_wrist_hand", "left_index_1"),
            ("left_index_1", "left_index_2"),
            ("left_index_2", "left_index_3"),
            ("left_index_3", "left_index_4"),
            ("left_wrist_hand", "left_middle_1"),
            ("left_middle_1", "left_middle_2"),
            ("left_middle_2", "left_middle_3"),
            ("left_middle_3", "left_middle_4"),
            ("left_wrist_hand", "left_ring_1"),
            ("left_ring_1", "left_ring_2"),
            ("left_ring_2", "left_ring_3"),
            ("left_ring_3", "left_ring_4"),
            ("left_wrist_hand", "left_pinky_1"),
            ("left_pinky_1", "left_pinky_2"),
            ("left_pinky_2", "left_pinky_3"),
            ("left_pinky_3", "left_pinky_4"),
            ("right_wrist_hand", "right_thumb_1"),
            ("right_thumb_1", "right_thumb_2"),
            ("right_thumb_2", "right_thumb_3"),
            ("right_thumb_3", "right_thumb_4"),
            ("right_wrist_hand", "right_index_1"),
            ("right_index_1", "right_index_2"),
            ("right_index_2", "right_index_3"),
            ("right_index_3", "right_index_4"),
            ("right_wrist_hand", "right_middle_1"),
            ("right_middle_1", "right_middle_2"),
            ("right_middle_2", "right_middle_3"),
            ("right_middle_3", "right_middle_4"),
            ("right_wrist_hand", "right_ring_1"),
            ("right_ring_1", "right_ring_2"),
            ("right_ring_2", "right_ring_3"),
            ("right_ring_3", "right_ring_4"),
            ("right_wrist_hand", "right_pinky_1"),
            ("right_pinky_1", "right_pinky_2"),
            ("right_pinky_2", "right_pinky_3"),
            ("right_pinky_3", "right_pinky_4"),
        ]
        skeleton = [
            [16, 14],
            [14, 12],
            [17, 15],
            [15, 13],
            [12, 13],
            [6, 12],
            [7, 13],
            [6, 7],
            [6, 8],
            [7, 9],
            [8, 10],
            [9, 11],
            [2, 3],
            [1, 2],
            [1, 3],
            [2, 4],
            [3, 5],
            [4, 6],
            [5, 7],
            [18, 19],
            [19, 20],
            [20, 21],
            [21, 22],
            [18, 23],
            [23, 24],
            [24, 25],
            [25, 26],
            [18, 27],
            [27, 28],
            [28, 29],
            [29, 30],
            [18, 31],
            [31, 32],
            [32, 33],
            [33, 34],
            [18, 35],
            [35, 36],
            [36, 37],
            [37, 38],
            [39, 40],
            [40, 41],
            [41, 42],
            [42, 43],
            [39, 44],
            [44, 45],
            [45, 46],
            [46, 47],
            [39, 48],
            [48, 49],
            [49, 50],
            [50, 51],
            [39, 52],
            [52, 53],
            [53, 54],
            [54, 55],
            [39, 56],
            [56, 57],
            [57, 58],
            [58, 59],
        ]

    elif mode == "hand":
        bodyparts2connect = [
            ("wrist_hand", "thumb_1"),
            ("thumb_1", "thumb_2"),
            ("thumb_2", "thumb_3"),
            ("thumb_3", "thumb_4"),
            ("wrist_hand", "index_1"),
            ("index_1", "index_2"),
            ("index_2", "index_3"),
            ("index_3", "index_4"),
            ("wrist_hand", "middle_1"),
            ("middle_1", "middle_2"),
            ("middle_2", "middle_3"),
            ("middle_3", "middle_4"),
            ("wrist_hand", "ring_1"),
            ("ring_1", "ring_2"),
            ("ring_2", "ring_3"),
            ("ring_3", "ring_4"),
            ("wrist_hand", "pinky_1"),
            ("pinky_1", "pinky_2"),
            ("pinky_2", "pinky_3"),
            ("pinky_3", "pinky_4"),
        ]
        skeleton = [
        [ 1,  2],
        [ 2,  3],
        [ 3,  4],
        [ 4,  5],
        [ 1,  6],
        [ 6,  7],
        [ 7,  8],
        [ 8,  9],
        [ 1, 10],
        [10, 11],
        [11, 12],
        [12, 13],
        [ 1, 14],
        [14, 15],
        [15, 16],
        [16, 17],
        [ 1, 18],
        [18, 19],
        [19, 20],
        [20, 21]
        ]
    return bodyparts2connect, skeleton
